version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # ext services port range
      - "127.0.0.1:53:53" # DNS config
      - "127.0.0.1:53:53/udp" # DNS config
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-2
  aws_cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    entrypoint: /bin/sh -c
    command: >
      "
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket surge-sync
      "
  build-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
      - aws_cli
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY_ID=test
      - PROJECT_ID=''
      - GIT_REPO_URL=''
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_BUCKET=surge-sync
      - KAFKA_BROKER=''
      - KAFKA_USERNAME=''
      - KAFKA_PASSWORD=''
